#
# Module manifest for module 'Bad-DBA'
#
# Generated by: Isaac Springer
#
# Updated: 2026-04-16 (Post-Remediation v2.0.0)
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Bad-DBA.psm1'

# Version number of this module.
ModuleVersion = '2.0.3'

# ID used to uniquely identify this module
GUID = 'be4c107f-3d40-4209-a5b8-2cf71999c674'

# Author of this module
Author = 'Isaac Springer'

# Company or vendor of this module
CompanyName = 'Isaac Springer'

# Copyright statement for this module
Copyright = '(c) 2026 Isaac Springer'

# Description of the functionality provided by this module
Description = 'Quick and dirty database administration PowerShell module for database administration with ZERO external dependencies. Including backup/restore operations, database mirroring, and automated deployment workflows.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '7.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module - EXPLICIT LIST (best practice)
FunctionsToExport = @(
    'Add-DbUser',
    'Close-AllSqlConnections',
    'Export-DbSchema',
    'Get-DbManifest',
    'Get-DbRoles',
    'Get-DbSchemas',
    'Get-DbSvcUser',
    'Get-DbUser',
    'Get-Endpoint',
    'Get-InstanceFQDN',
    'Get-Namespaces',
    'Get-OpenTrans',
    'Get-SnapshotState',
    'Get-SqlDefaultLocation',
    'Get-SysDatabases',
    'Invoke-AllSqlScripts',
    'Invoke-DbShrink',
    'Invoke-Sql',
    'New-BackupFull',
    'New-BackupLog',
    'New-ConnectionString',
    'New-DbUser',
    'New-Endpoint',
    'New-Mirror',
    'Restore-BackupFull',
    'Restore-BackupLog',
    'Set-DbUserSchema',
    'Set-EndpointACL',
    'Set-RecoveryModel'
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @('Get-DfltLoc')

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('SQL', 'SQLServer', 'Database', 'Backup', 'Restore', 'Mirroring', 'HADR', 'ADO.NET')

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/onyxhat/Bad-DBA/refs/heads/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/onyxhat/Bad-DBA'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
Version 2.0.0 - Major Remediation Release
==========================================

SECURITY HARDENING:
- Eliminated SQL injection vulnerabilities via parameterized queries
- Added PSCredential support for secure authentication
- Guaranteed connection cleanup prevents resource leaks

MODERNIZATION:
- Replaced Write-Host with proper PowerShell streams
- PSCustomObject output for pipeline compatibility (-AsDataTable for legacy)
- Removed SMO assembly dependency (pure T-SQL)

CODE QUALITY:
- Explicit column lists in all queries
- DRY principles with internal helper functions
- Consistent Verb-Noun naming conventions

FEATURE PARITY:
- New-Endpoint now supports custom port configuration
- Restore-BackupFull implements -WithRecovery switch
- Set-RecoveryModel supports all three SQL Server recovery models

BREAKING CHANGES: None - 100% backward compatible

For detailed changes, see PHASE1-IMPLEMENTATION-SUMMARY.md, PHASE2-SUMMARY.md, and PHASE3-SUMMARY.md
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
